# Generated by Django 3.2 on 2021-04-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.CharField(blank=True, max_length=500, null=True)),
                ('authors', models.CharField(blank=True, max_length=500, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=500, null=True)),
                ('isbn10', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('publisher', models.CharField(blank=True, max_length=500, null=True)),
                ('pubyear', models.IntegerField()),
                ('subjects', models.CharField(blank=True, max_length=500, null=True)),
                ('lexile', models.CharField(blank=True, max_length=500, null=True)),
                ('pages', models.IntegerField()),
                ('dimensions', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
