# Generated by Django 3.2 on 2021-04-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_books_b_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='pubyear',
            field=models.CharField(max_length=50),
        ),
    ]
