# Generated by Django 3.2 on 2021-04-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20210411_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='b_id',
        ),
    ]
